# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 147b776e7ba0f0e88471835d1e9eeba7757d33e32b19e8a5f8c74725a608a4af394dd759569eeffdbae494bce19b974f486f1964b5b62cd32fde36360aeb78cc

test:
  secret_key_base: 3474ff7cd666bca981fa9f7aa24747dee13fbf31ea45d13824451b39725d219b1b09251eb5b686cc514ee4cb11f9042095431d8d66a61064e1216eee9f027ce6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
